LOGGER_PREFIX = 'messaging_rabbitmq'

ERROR_RETRY_EXCHANGE = '_error_retry'
ERROR_DEAD_EXCHANGE = '_error_dead'
ERROR_RETURN_EXCHANGE = '_error_return'

ERROR_RETRY_QUEUE_SUFFIX = '_error_retry'
ERROR_DEAD_QUEUE_SUFFIX = '_error_dead'

ERROR_ROUTING_KEY_PREFIX = 'error.'

DEFAULT_ERROR_MAX_RETRY_ATTEMPTS = 5
DEFAULT_ERROR_RETRY_TTL_MSECONDS = 30_000
MIN_ERROR_RETRY_TTL_MSECONDS = 1_000