"""first_migration

Revision ID: aee62ab0e9cf
Revises: 
Create Date: 2024-08-12 14:15:16.143773+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aee62ab0e9cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('task_type', sa.Enum('phone', 'email', 'gpt', name='tasktypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_service'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integration_service')
    # ### end Alembic commands ###
